---
#these tasks installs and confiures nginx on a ubuntu server

#the apache server
- name: install apache
  apt: pkg=apache2 state=present
  sudo: True

#a web browser like lymx is necessary for the apachectl status command to work
- name: install lynx
  apt: pkg=lynx state=present
  sudo: True

#prerequisite for apache virtual hosts (which we use everywhere)
- name: copy virtual.conf
  copy: src=virtual.conf dest=/etc/apache2/conf.d/virtual.conf
  sudo: True