---

#install and configure a base server

- name: deploying base server
  hosts: all
  sudo: True
  vars_files:
    - vars/main.yml
  roles:
    - base-requirements
    - base-groups
    - ANXS.generic-users
    - Stouts.openssh
#    - iptables
#    - fail2ban
