---

# create site root directory
- name: create site directory
  file: path=/var/www/{{ nginx_server_name }} state=directory
  sudo: True

#copy virtual host file
- name: copy virtual host file
  template: src={{ nginx_vhost_template | default vhost_default.txt }} dest=/etc/nginx/sites-available/{{ nginx_server_name }}
  sudo: True

#create symlink in sites-enabled
- name: add host file to sites-enabled
  command: ln -s /etc/nginx/sites-available/{{ nginx_server_name }} /etc/nginx/sites-enabled/{{ nginx_server_name }}
  sudo: True
  ignore_errors: True

#restart apache so it picks up these changes
- name: restart nginx
  service: name=nginx state=restarted
  sudo: True
