---

- name: update apt cache
  apt: update_cache=yes
  sudo: True

- name: install apt-requirements
  apt: name={{ item }} state=present
  sudo: True
  with_items:
      - vim
      - curl 
      - screen
      - tmux
      - htop
      - ipython
      - python 
      - pip 

