---

- name: create the sysadmin group
  group: name=sysadmin state=present gid=30000
  sudo: True

- name: allow the sysadmin group to sudo
  copy: src=etc/sudoers.d/sysadmin dest=/etc/sudoers.d/sysadmin validate='visudo -cf %s' mode=440
  sudo: True

- name: remove old users
  user: name={{ item }} state=absent force=true
  with_items: old_users
  sudo: True

- name: add users
  user: name={{ item.name }} state=present shell={{ item.shell }}  groups={{ item.groups }} uid={{  item.uid  }}
  with_items: current_users
  sudo: True

- name: copy ssh keys
  authorized_key: user={{ item.0.name }} key="{{ lookup('file', item.1) }}"
  with_subelements:
     - current_users
     - authorized
