---

#install the mysql server and necessary drivers

#base package
- name: install mysql server
  apt: pkg=mysql-server state=installed
  sudo: True

#php drivers
- name: install php5 PDO package
  apt: pkg=php5-mysql state=installed
  sudo: True

#python drivers (required by some apps)
- name: install the python-mysqldb package
  apt: pkg=python-mysqldb state=installed
  sudo: True