---

#install php5

#base packages
- name: install php5
  apt: pkg=php5 state=present
  sudo: True

- name: install php5-common
  apt: pkg=php5-common state=present
  sudo: True

- name: install php5-cli
  apt: pkg=php5-cli state=present
  sudo: True
  
#require for nginx fastcgi php processor
- name: install php5-fpm
  apt: pkg=php5-fpm state=present
  sudo: True
