---

#instal fail2ban

#used to set up basic security on ubuntu 12.04
#follows the how-to at http://feross.org/how-to-setup-your-linode/

#
#install and configure fail2ban
#
- name: install fail2ban
  apt: pkg=fail2ban state=installed
  sudo: True

- name: copy jail.conf to jail.local
  command: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
  sudo: True

- name: restart fail2ban service
  service: name=fail2ban state=restarted
  sudo: True
